/* Auto-generated by genmsg_cpp for file /home/yuri/WorkSpace/ROS/arm/msg/PS2.msg */
#ifndef ARM_MESSAGE_PS2_H
#define ARM_MESSAGE_PS2_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm
{
template <class ContainerAllocator>
struct PS2_ {
  typedef PS2_<ContainerAllocator> Type;

  PS2_()
  : A(0)
  , B(0)
  , C(0)
  {
  }

  PS2_(const ContainerAllocator& _alloc)
  : A(0)
  , B(0)
  , C(0)
  {
  }

  typedef int32_t _A_type;
  int32_t A;

  typedef int32_t _B_type;
  int32_t B;

  typedef int32_t _C_type;
  int32_t C;


  typedef boost::shared_ptr< ::arm::PS2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm::PS2_<ContainerAllocator>  const> ConstPtr;
}; // struct PS2
typedef  ::arm::PS2_<std::allocator<void> > PS2;

typedef boost::shared_ptr< ::arm::PS2> PS2Ptr;
typedef boost::shared_ptr< ::arm::PS2 const> PS2ConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm::PS2_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm::PS2_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm::PS2_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm::PS2_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm::PS2_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e7a68ce4e0b75a9719b4950a7069c9d4";
  }

  static const char* value(const  ::arm::PS2_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe7a68ce4e0b75a97ULL;
  static const uint64_t static_value2 = 0x19b4950a7069c9d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm::PS2_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm/PS2";
  }

  static const char* value(const  ::arm::PS2_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm::PS2_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 A\n\
int32 B\n\
int32 C\n\
";
  }

  static const char* value(const  ::arm::PS2_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arm::PS2_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm::PS2_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.A);
    stream.next(m.B);
    stream.next(m.C);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct PS2_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm::PS2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm::PS2_<ContainerAllocator> & v) 
  {
    s << indent << "A: ";
    Printer<int32_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int32_t>::stream(s, indent + "  ", v.B);
    s << indent << "C: ";
    Printer<int32_t>::stream(s, indent + "  ", v.C);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_MESSAGE_PS2_H

